--- #YAML:1.0
name:                Linux-Apple-Laptop-LED
version:             0.06
abstract:            Turn the front LED on Apple laptops on and off via ADB
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
